# Generated by Django 2.1.5 on 2019-01-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
