# Generated by Django 2.1.5 on 2019-01-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190112_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('descrption', models.TextField()),
                ('genre', models.CharField(max_length=1000)),
                ('isbn', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
