# Generated by Django 2.1.5 on 2019-01-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190112_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=256),
        ),
    ]
