# Generated by Django 2.1.5 on 2019-01-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190113_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='publication_date',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
