# Generated by Django 2.1.5 on 2019-02-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='user_id',
        ),
    ]
